<?php

namespace AppBundle\Repository;

/**
 * ChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find one checklist by issue and id
     * @param $issue
     * @param $checklist_id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByIssueAndId( $issue, $checklist_id ) 
    {
        return $this->createQueryBuilder('c')
            ->where('c.issue = :issue')
            ->andWhere('c.id = :id')
            ->setParameter('issue', $issue)
            ->setParameter('id', $checklist_id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
