<?php

namespace AppBundle\Repository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find one issue by client_key, project_key, issue_id and issue_key
     * @param $projectKey
     * @param $issueId
     * @param $issueKey
     * @param $clientKey
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneIssue($projectKey, $issueId, $issueKey, $clientKey) 
    {
        return $this->createQueryBuilder('i')
            ->andWhere('i.projectKey = :projectKey')
            ->andWhere('i.issueId = :issueId')
            ->andWhere('i.issueKey = :issueKey')
            ->andWhere('i.clientKey = :clientKey')
            ->setParameter('projectKey', $projectKey)
            ->setParameter('issueId', $issueId)
            ->setParameter('issueKey', $issueKey)
            ->setParameter('clientKey', $clientKey)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
